=== Protino/templator/src/test/resources/EntranceExams/input.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT topic ((reading-test))>
<!ATTLIST topic
	t_id CDATA #REQUIRED
	t_name CDATA #REQUIRED
>
<!ELEMENT test-set ((topic)+)>
<!ELEMENT reading-test ((doc, question+))>
<!ATTLIST reading-test
	r_id CDATA #REQUIRED
>
<!ELEMENT question ((q_str, answer+))>
<!ATTLIST question
	q_id CDATA #REQUIRED
>
<!ELEMENT q_str (#PCDATA)>
<!ELEMENT doc (#PCDATA)>
<!ATTLIST doc
	d_id CDATA #REQUIRED
>
<!ELEMENT answer (#PCDATA)>
<!ATTLIST answer
	a_id (5 | 4 | 3 | 2 | 1) #REQUIRED
>

=== Protino/templator/src/test/resources/EntranceExams/clef2014-qatrack-exam-reading-testlabel-en.xml
<?xml version="1.0" ?>
<!DOCTYPE test-set SYSTEM "input.dtd">
<test-set>
  <topic t_id="0" t_name="Entrance Exam">
    <reading-test r_id="13">
      <doc d_id="1">When is a person old? There are many individuals who still seem 'young' at seventy or more, while others appear 'old' in their fifties. From another point of view, sumo wrestlers, for instance, are 'old' in their thirties, whereas artists' best years may come in their sixties or even later. But in general, people are old when society considers them to be old, that is, when they retire from work at around the age of sixty or sixty-five. Nowadays, however, the demand for new work skills is making more and more individuals old before their time. Although older workers tend to be dependable, and have much to offer from their many years of experience, they are put at a disadvantage by rapid developments in technology. Older people usually find it more difficult to acquire the new skills required by technological changes, and they do not enjoy the same educational opportunities as young workers. When they finally leave work and retire, people face further problems. The majority receive little or no assistance in adjusting to their new situation in the community. Moreover, since society at present appears to have no clear picture of what place its older members should occupy, it is unable to offer them enough opportunities to have satisfying social roles after they retire. In the past, the old used to be looked upon as experts in solving various problems of life. Today, however, they are no longer regarded as such and are seldom expected to play significant roles in social, economic and community affairs. With the number of older people in the population rapidly increasing, we need greatly to increase and improve the opportunities provided for them so that they can participate in society with dignity and respect.  </doc>
      <question q_id="1">
        <q_str>People are normally regarded as old when</q_str>
        <answer a_id="1">they are in their fifties</answer>
        <answer a_id="2" correct="Yes">they are judged to be old by to society</answer>
        <answer a_id="3">they consider themselves too old to work</answer>
        <answer a_id="4">they reach the age of seventy</answer>
      </question>
      <question q_id="2">
        <q_str>Changes in technology can</q_str>
        <answer a_id="1">enable older workers to make better use of their experience</answer>
        <answer a_id="2">give older people opportunities for new jobs</answer>
        <answer a_id="3">make it easier for older workers to acquire new skills</answer>
        <answer a_id="4" correct="Yes">make older people's knowledge and skills out of date</answer>
      </question>
      <question q_id="3">
        <q_str>After finally retiring, most people</q_str>
        <answer a_id="1">are given new social roles by society</answer>
        <answer a_id="2">do not need assistance in making the necessary adjustments</answer>
        <answer a_id="3">have few disadvantages in their new situation</answer>
        <answer a_id="4" correct="Yes">have to work out their social roles largely for themselves</answer>
      </question>
      <question q_id="4">
        <q_str>According to the fourth paragraph, the position of old people in society today largely depends on</q_str>
        <answer a_id="1">how many problems they are able to solve</answer>
        <answer a_id="2">the age at which they finally retire from their work</answer>
        <answer a_id="3">the rapid increase in the number of retired people in the community</answer>
        <answer a_id="4" correct="Yes">what opportunities they are given by society</answer>
      </question>
    </reading-test>
    <reading-test r_id="14">
      <doc d_id="1">It began when I was a 16-year-old high school student. I was reading a popular youth magazine when I noticed a list of addresses of young people from all over the world who were seeking pen pals in Japan. I had often seen boys and girls in my class receiving fat airmail envelopes from overseas. Having a pen pal was the fashion of the day. Why shouldn't I get one, too? So I picked out the address of one &quot;Margaret K.&quot; in Boston and, remembering that a girl from my class had once told me young ladies like to read letters on pink paper, I went out to buy some. &quot;Dear Pen Pal,&quot; I began, but then stopped. I was very nervous and really didn't know how to continue or what to say. After much effort I finished the letter, though it didn't even fill one page. The reply from faraway America came sooner than I had expected. &quot;I was surprised to receive your letter,&quot; Margaret wrote. &quot;I don't know how my address got into a magazine in Japan, because I have never asked for a pen pal, but it's so nice hearing from someone in such a fascinating country, and I look forward to corresponding with you.&quot; I don't know how many times I read that letter. When writing to Margaret, I took care not to say anything that might upset her. While English came naturally to Margaret, for me it was a foreign language, so I wrote only about everyday matters. But somewhere in my heart there was a sense of romance which I dared not express. For her part, though Margaret wrote long letters, she revealed little about herself. Big envelopes containing books, magazines, and other small gifts began to arrive. I had no doubt that Margaret was a rich American girl, and that she was as beautiful as her attractive gifts. I felt that our pen friendship was a great success. However, there was one thing I couldn't get out of my mind. I knew it would be impolite to ask a girl her age, but thought it would be all right to ask her to send a picture. So I wrote the request and at last came the reply. Margaret said simply that she had no suitable pictures of herself at that time, but that she would send me one someday. She added that &quot;the average American girl&quot; was much nicer-looking than she was. Years went by. Our letters became less frequent but we never lost touch. Meanwhile, I graduated from college, got a job, married and had children. I still hoped that I might be able to meet Margaret someday and that my family might also meet her. Then, one day I received a large airmail envelope addressed in unfamiliar handwriting. It contained a few magazines and a note from a lady named Alice. &quot;I'm very sorry to inform you,&quot; the note said, &quot;that Margaret died in an accident last month while she was driving home from church. We had been close friends for the past sixty years - ever since we were in high school together. Margaret often mentioned how happy she was to hear from you. Though she lived alone, she had many friends, and always tried to help others, both far and near.&quot; There was also a photograph enclosed. Margaret had asked her friend to send it only in the case of her death. The face in the picture was one of great beauty and kindness. It was a face I would have loved even when I was still young and she was already quite old.  fs</doc>
      <question q_id="1">
        <q_str>What made the author decide to have a pen pal in a foreign country?</q_str>
        <answer a_id="1">He happened to receive a fat airmail envelope from abroad.</answer>
        <answer a_id="2" correct="Yes">He wanted to do the same as many of his classmates.</answer>
        <answer a_id="3">He wanted to have his address printed in a magazine.</answer>
        <answer a_id="4">He was urged to have one by a classmate.</answer>
      </question>
      <question q_id="2">
        <q_str>How did the author obtain Margaret's address?</q_str>
        <answer a_id="1" correct="Yes">He found it in a popular magazine.</answer>
        <answer a_id="2">He received it from one of his classmates.</answer>
        <answer a_id="3">He selected it from a list given by his teacher.</answer>
        <answer a_id="4">He wrote to a popular magazine for her address.</answer>
      </question>
      <question q_id="3">
        <q_str>Why did the author ask Margaret for her picture?</q_str>
        <answer a_id="1">Because he thought it polite to ask for a picture.</answer>
        <answer a_id="2" correct="Yes">Because he wanted to know how old she was.</answer>
        <answer a_id="3">Because he wanted to show her picture to his classmates.</answer>
        <answer a_id="4">Because his classmates had pictures of their pen pals.</answer>
      </question>
      <question q_id="4">
        <q_str>Why did Margaret's friend write to the author?</q_str>
        <answer a_id="1" correct="Yes">Because she had been asked by Margaret to send a photograph to the author after she died.</answer>
        <answer a_id="2">Because she had been asked by Margaret to write to the author about their sixty-year friendship.</answer>
        <answer a_id="3">Because she thought it was the right thing to do, although Margaret had requested her not to.</answer>
        <answer a_id="4">Because she thought that she could take Margaret's place as the author's pen pal.</answer>
      </question>
      <question q_id="5">
        <q_str>Why didn't Margaret want the author to see her picture while she was alive?</q_str>
        <answer a_id="1">Because she believed herself to be just an average-looking girl.</answer>
        <answer a_id="2">Because she did not have any pictures of herself.</answer>
        <answer a_id="3">Because she thought it impolite for a boy to ask for a picture.</answer>
        <answer a_id="4" correct="Yes">Because she thought it would spoil his image of her.</answer>
      </question>
      <question q_id="6">
        <q_str>How did the author feel when he saw Margaret's photograph?</q_str>
        <answer a_id="1">He felt that she looked just as he had imagined.</answer>
